### ISSUE TITLE
Option to quit after both EBS and ENI are attached

### ISSUE THREAD

**Issue by javefang** [UKHomeOffice/smilodon#7]
Hi there,

Thanks for sharing this great utility! It looks really useful and does the job here.

I noticed the smilodon process will run forever in a loop which should attempt to re-attach EBS or ENI if any of those gets detached. In our use-case. We are running smilodon in Cloud-Init, which is part of a bigger Terraform deployment. We really just need smilodon to do the attachment once and quit. Is it possible to add a flag called "-once" so that it quit the process immediately when both EBS and ENI are attached? Happy to provide a PR.

Thanks,

Xinghong

**Comment by vaijab** [comment]
@javefang that is not such a bad idea. I will add an option to allow to disable daemon mode `--daemon=false`.

**Comment by vaijab** [comment]
@javefang btw, if you feel like raising a PR, please go ahead. I think adding a new cli flag `--daemon=true` by default would be ideal.

**Comment by javefang** [comment]
@vaijab here is my first try https://github.com/UKHomeOffice/smilodon/pull/8

**Comment by vaijab** [comment]
@javefang looks good. I merged it. If everything works as expected, please close this issue.

**Comment by javefang** [comment]
All working well, thanks! Would you consider making a release at some point?
